projects:
  lazy-appsync:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: l2twrk3pifewnpxxr2m7atwuvm
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: us-east-2
      endpoints:
        prod: >-
          https://retuqsjuyrb55g3mex5kin3ddu.appsync-api.us-east-2.amazonaws.com/graphql
